### ISSUE TITLE
Support Angular 10

### ISSUE THREAD

**Issue by davidshen84** [maxisam/ngx-window-token#29]
Blocking https://github.com/maxisam/ngx-clipboard/issues/245

**Comment by davidshen84** [comment]
@maxisam The `library-host` itself depends on `ngx-window-token`. How should I update the root project? Please advice. I do not have experience working with a project structure like this.

**Comment by maxisam** [comment]
Just need to upgrade ngx-window-token as well.

**Comment by davidshen84** [comment]
Do you mean I should go to `projects/ngx-window-token`, and update and publish it, then update the `library-host` project?

**Comment by maxisam** [comment]
If you have time, please make a pull request to ngx-window-token and i will merge it later.
