### ISSUE TITLE
Can't import the named export 'InjectionToken' from non EcmaScript module

### ISSUE THREAD

**Issue by bkimminich** [maxisam/ngx-window-token#46]
Since `6.0.0` I'm getting this error in my CI/CD pipeline:

```
Error: ./node_modules/ngx-window-token/fesm2015/ngx-window-token.mjs 3:19-33
Can't import the named export 'InjectionToken' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/home/runner/work/juice-shop/juice-shop/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (/home/runner/work/juice-shop/juice-shop/frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/home/runner/work/juice-shop/juice-shop/frontend/node_modules/webpack/lib/Compilation.js:1463:22)
    at /home/runner/work/juice-shop/juice-shop/frontend/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/home/runner/work/juice-shop/juice-shop/frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at eval (eval at create (/home/runner/work/juice-shop/juice-shop/frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:57:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 @ ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```
(https://github.com/juice-shop/juice-shop/runs/4208560126?check_suite_focus=true#step:6:410)

This module is only a peer dependency of my project (through `ngx-clipboard`) and I am not sure if it's an issue here or there. I've added a pinned dependency to `"ngx-window-token": "^5.0.0"` for now, which is fine as a workaround.

Just opening this ticket in case there's been some accidental breaking change. Changelog doesn't mention any yet, so maybe it's just something that needs to be added there.

Cheers!

**Comment by maxisam** [comment]
yes, there is a breaking change for v6. It only works with angular 13 because Ivy packaging.
https://github.com/maxisam/ngx-window-token/tree/chore/ng13-upgrade#breaking-change-after-version-600

**Comment by maxisam** [comment]
Previous statement about only working with Angular >= 13 might not be true. 

I just upgraded ngx-clipboard to 15.0.0 as well. According to the doc, it should work with Angular <= 12 . Could you try it?

**Comment by bkimminich** [comment]
Still fails, but more noisy now: https://github.com/juice-shop/juice-shop/runs/4215099005?check_suite_focus=true

**Comment by maxisam** [comment]
@bkimminich Thanks for the feedback. I guess it means if the library built with Angular 13, it won't work with previous version.
Maybe I misunderstood what this means https://angular.io/guide/angular-package-format#partial-compilation

Anyway, please stick with ngx-clipboard before you upgrade to angular 13 and lock the dependency for now. I will publish a fix on 14 to lock the dependency

Sorry for all the confusion. Thanks!

**Comment by maxisam** [comment]
@bkimminich could you try 14.0.2?

**Comment by bkimminich** [comment]
https://github.com/juice-shop/juice-shop/actions/runs/1468631288

Looks promising so far...

**Comment by ccravens** [comment]
@maxisam looks like it worked for me as well, I'm continuing testing but so far so good, thank you for this quick response!

**Comment by Sam-Lin-MillersLab** [comment]
thank you for testing

**Comment by weihan1394** [comment]
@maxisam this works for me too! Thank you.

**Comment by maxisam** [comment]
Thanks guys!

**Comment by ghost** [comment]
This problem to solve that you can  install ' npm i ngx-inject ' version 4.0.0.
after the run 'ng serve' command then Problem is fix.

**Comment by pradnya2196** [comment]
i tried all the above possible solutions, but none of them works for me! :(

**Comment by maxisam** [comment]
@pradnya2196 You have couple options. 1. Just copy the code to your project. It is just 1 line of code. 2 ask this on StackOverflow.
