### ISSUE TITLE
Error ngx-window-token/lib/window.ts (2,22): Error during template compile of 'window'

### ISSUE THREAD

**Issue by Ditmar** [maxisam/ngx-window-token#53]
I want to report this error in the new version, 6.0.0

![Screen Shot 2021-11-21 at 21 44 19](https://user-images.githubusercontent.com/317151/142788835-b3e0405c-c7db-48a9-b2e6-d97e21ca941d.png)

**Comment by maxisam** [comment]
What is your angular version? V6 only work with Angular 13

https://github.com/maxisam/ngx-window-token#breaking-change-after-version-600

**Comment by rp0m** [comment]
> What is your angular version? V6 only work with Angular 13
> 
> https://github.com/maxisam/ngx-window-token#breaking-change-after-version-600

Having the same issue as OP. Did not know that v6 only works with Angular 13 as the https://www.npmjs.com/package/ngx-window-token states dependencies as `Angular >=6.0.0`, which, based on your reply above, is no longer valid and should be updated?

Update: I can see that https://github.com/maxisam/ngx-window-token/blob/master/README.md has been updated with Angular v13 comment, but the readme on https://www.npmjs.com/package/ngx-window-token has not. I assumed it was not published accidentally - worth doing!

**Comment by maxisam** [comment]
Yeah, I forgot to update ReadMe when I push.
